
user = {
    "_id": "user0",
    "firstName": "Alice",
    "lastName": "Smith",
    "email": "alice.smith@example.com",
    "password": "758b93a1de5cb4bcf288b598364e3cb9a59f500c881ad89814a680864dc0cea00be4f563fe66d7df48ab57ddada08fe3f03adfdafd9bf785b2b53c7d36f75b99",
    "role": "user",
    "phone": "+12345678901",
    "status": "active",
    "dateOfBirth": "1995-03-15",
    "gender": "female",
    "height": 165,
    "photo": {
            "url": "https://example.com/photos/alice.jpg",
            "publicId": "alice_001"
    },
    "address": "123 Main St",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "zipCode": "10001",
    "location": {"type": "Point", "coordinates": [-73.985, 40.748]},
    "lastLocationUpdate": "2025-09-19T17:37:00Z",
    "nativeLanguage": "English",
    "spokenLanguages": ["English", "Spanish"],
    "hobbies": ["reading", "hiking", "cooking"],
    "interests": ["travel", "music", "photography"],
    "favoriteColors": ["blue", "green"],
    "minAge": "25",
    "maxAge": "35",
    "whatBringsYouHere": "friendship",
    "genderInterest": "male",
    "pets": ["dog"],
    "education": "Bachelor's",
    "lookingFor": ["friendship", "casual"],
    "religion": "Christian",
    "images": [
            {
                "url": "https://example.com/images/alice1.jpg",
                "publicId": "alice_img1"
            },
        {
                "url": "https://example.com/images/alice2.jpg",
                "publicId": "alice_img2"
        }
    ],
    "completionPercentage": 95
}

data = [
    {
        "_id": "user1",
        "firstName": "Bob",
        "lastName": "Johnson",
        "email": "bob.johnson@example.com",
        "password": "hashedPassword2",
        "role": "user",
        "phone": "+12345678902",
        "status": "active",
        "dateOfBirth": "1990-07-22",
        "gender": "male",
        "height": 180,
        "photo": {
            "url": "https://example.com/photos/bob.jpg",
            "publicId": "bob_001"
        },
        "address": "456 Elm St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10002",
        "location": {"type": "Point", "coordinates": [-73.99, 40.735]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "English",
        "spokenLanguages": ["English", "French"],
        "hobbies": ["gaming", "cycling", "cooking"],
        "interests": ["technology", "sports"],
        "favoriteColors": ["red", "black"],
        "minAge": "20",
        "maxAge": "30",
        "whatBringsYouHere": "relationship",
        "genderInterest": "female",
        "pets": ["cat"],
        "education": "Master's",
        "lookingFor": ["relationship"],
        "religion": "None",
        "images": [
            {"url": "https://example.com/images/bob1.jpg", "publicId": "bob_img1"}
        ],
        "completionPercentage": 90
    },
    {
        "_id": "user2",
        "firstName": "Clara",
        "lastName": "Rodriguez",
        "email": "clara.rodriguez@example.com",
        "password": "hashedPassword3",
        "role": "user",
        "phone": "+12345678903",
        "status": "active",
        "dateOfBirth": "1998-11-10",
        "gender": "female",
        "height": 160,
        "photo": {
            "url": "https://example.com/photos/clara.jpg",
            "publicId": "clara_001"
        },
        "address": "789 Pine St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10003",
        "location": {"type": "Point", "coordinates": [-73.975, 40.74]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "Spanish",
        "spokenLanguages": ["Spanish", "English"],
        "hobbies": ["dancing", "reading"],
        "interests": ["art", "travel"],
        "favoriteColors": ["pink", "purple"],
        "minAge": "22",
        "maxAge": "32",
        "whatBringsYouHere": "friendship",
        "genderInterest": "male",
        "pets": ["dog", "cat"],
        "education": "High School",
        "lookingFor": ["friendship"],
        "religion": "Catholic",
        "images": [],
        "completionPercentage": 85
    },
    {
        "_id": "user3",
        "firstName": "David",
        "lastName": "Lee",
        "email": "david.lee@example.com",
        "password": "hashedPassword4",
        "role": "user",
        "phone": "+12345678904",
        "status": "active",
        "dateOfBirth": "1988-02-05",
        "gender": "male",
        "height": 175,
        "photo": {
            "url": "https://example.com/photos/david.jpg",
            "publicId": "david_001"
        },
        "address": "101 Oak St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10004",
        "location": {"type": "Point", "coordinates": [-73.98, 40.745]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "English",
        "spokenLanguages": ["English", "Mandarin"],
        "hobbies": ["photography", "traveling"],
        "interests": ["music", "technology"],
        "favoriteColors": ["blue", "black"],
        "minAge": "25",
        "maxAge": "40",
        "whatBringsYouHere": "relationship",
        "genderInterest": "female",
        "pets": [],
        "education": "PhD",
        "lookingFor": ["relationship", "friendship"],
        "religion": "Buddhist",
        "images": [
            {
                "url": "https://example.com/images/david1.jpg",
                "publicId": "david_img1"
            }
        ],
        "completionPercentage": 92
    },
    {
        "_id": "user4",
        "firstName": "Emma",
        "lastName": "Brown",
        "email": "emma.brown@example.com",
        "password": "hashedPassword5",
        "role": "user",
        "phone": "+12345678905",
        "status": "active",
        "dateOfBirth": "1993-09-20",
        "gender": "female",
        "height": 170,
        "photo": {
            "url": "https://example.com/photos/emma.jpg",
            "publicId": "emma_001"
        },
        "address": "202 Cedar St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10005",
        "location": {"type": "Point", "coordinates": [-73.987, 40.75]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "English",
        "spokenLanguages": ["English"],
        "hobbies": ["yoga", "cooking"],
        "interests": ["fitness", "food"],
        "favoriteColors": ["green", "yellow"],
        "minAge": "28",
        "maxAge": "38",
        "whatBringsYouHere": "casual",
        "genderInterest": "male",
        "pets": ["dog"],
        "education": "Bachelor's",
        "lookingFor": ["casual"],
        "religion": "None",
        "images": [
            {"url": "https://example.com/images/emma1.jpg", "publicId": "emma_img1"}
        ],
        "completionPercentage": 88
    },
    {
        "_id": "user5",
        "firstName": "Frank",
        "lastName": "Wilson",
        "email": "frank.wilson@example.com",
        "password": "hashedPassword6",
        "role": "user",
        "phone": "+12345678906",
        "status": "active",
        "dateOfBirth": "1992-04-12",
        "gender": "male",
        "height": 185,
        "photo": {
            "url": "https://example.com/photos/frank.jpg",
            "publicId": "frank_001"
        },
        "address": "303 Birch St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10006",
        "location": {"type": "Point", "coordinates": [-73.995, 40.742]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "English",
        "spokenLanguages": ["English", "German"],
        "hobbies": ["sports", "gaming"],
        "interests": ["sports", "movies"],
        "favoriteColors": ["red", "blue"],
        "minAge": "20",
        "maxAge": "35",
        "whatBringsYouHere": "friendship",
        "genderInterest": "female",
        "pets": ["cat", "bird"],
        "education": "Associate's",
        "lookingFor": ["friendship"],
        "religion": "Christian",
        "images": [],
        "completionPercentage": 80
    },
    {
        "_id": "user6",
        "firstName": "Grace",
        "lastName": "Martinez",
        "email": "grace.martinez@example.com",
        "password": "hashedPassword7",
        "role": "user",
        "phone": "+12345678907",
        "status": "active",
        "dateOfBirth": "1997-06-25",
        "gender": "female",
        "height": 158,
        "photo": {
            "url": "https://example.com/photos/grace.jpg",
            "publicId": "grace_001"
        },
        "address": "404 Maple St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10007",
        "location": {"type": "Point", "coordinates": [-73.978, 40.738]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "Spanish",
        "spokenLanguages": ["Spanish", "English", "French"],
        "hobbies": ["painting", "traveling"],
        "interests": ["art", "culture"],
        "favoriteColors": ["purple", "pink"],
        "minAge": "22",
        "maxAge": "30",
        "whatBringsYouHere": "relationship",
        "genderInterest": "male",
        "pets": ["dog"],
        "education": "Bachelor's",
        "lookingFor": ["relationship"],
        "religion": "Catholic",
        "images": [
            {
                "url": "https://example.com/images/grace1.jpg",
                "publicId": "grace_img1"
            }
        ],
        "completionPercentage": 93
    },
    {
        "_id": "user7",
        "firstName": "Henry",
        "lastName": "Davis",
        "email": "henry.davis@example.com",
        "password": "hashedPassword8",
        "role": "user",
        "phone": "+12345678908",
        "status": "active",
        "dateOfBirth": "1987-12-30",
        "gender": "male",
        "height": 190,
        "photo": {
            "url": "https://example.com/photos/henry.jpg",
            "publicId": "henry_001"
        },
        "address": "505 Spruce St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10008",
        "location": {"type": "Point", "coordinates": [-73.97, 40.755]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "English",
        "spokenLanguages": ["English"],
        "hobbies": ["basketball", "reading"],
        "interests": ["sports", "literature"],
        "favoriteColors": ["green", "black"],
        "minAge": "30",
        "maxAge": "40",
        "whatBringsYouHere": "relationship",
        "genderInterest": "female",
        "pets": [],
        "education": "Master's",
        "lookingFor": ["relationship"],
        "religion": "None",
        "images": [
            {
                "url": "https://example.com/images/henry1.jpg",
                "publicId": "henry_img1"
            }
        ],
        "completionPercentage": 90
    },
    {
        "_id": "user8",
        "firstName": "Isabella",
        "lastName": "Garcia",
        "email": "isabella.garcia@example.com",
        "password": "hashedPassword9",
        "role": "user",
        "phone": "+12345678909",
        "status": "active",
        "dateOfBirth": "1994-08-14",
        "gender": "female",
        "height": 162,
        "photo": {
            "url": "https://example.com/photos/isabella.jpg",
            "publicId": "isabella_001"
        },
        "address": "606 Willow St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10009",
        "location": {"type": "Point", "coordinates": [-73.982, 40.732]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "Spanish",
        "spokenLanguages": ["Spanish", "English"],
        "hobbies": ["dancing", "cooking"],
        "interests": ["dance", "food"],
        "favoriteColors": ["red", "yellow"],
        "minAge": "25",
        "maxAge": "35",
        "whatBringsYouHere": "friendship",
        "genderInterest": "male",
        "pets": ["cat"],
        "education": "Bachelor's",
        "lookingFor": ["friendship", "casual"],
        "religion": "Catholic",
        "images": [],
        "completionPercentage": 87
    },
    {
        "_id": "user9",
        "firstName": "James",
        "lastName": "Taylor",
        "email": "james.taylor@example.com",
        "password": "hashedPassword10",
        "role": "user",
        "phone": "+12345678910",
        "status": "active",
        "dateOfBirth": "1991-01-18",
        "gender": "male",
        "height": 178,
        "photo": {
            "url": "https://example.com/photos/james.jpg",
            "publicId": "james_001"
        },
        "address": "707 Ash St",
        "city": "New York",
        "state": "NY",
        "country": "USA",
        "zipCode": "10010",
        "location": {"type": "Point", "coordinates": [-73.988, 40.747]},
        "lastLocationUpdate": "2025-09-19T17:37:00Z",
        "nativeLanguage": "English",
        "spokenLanguages": ["English", "Italian"],
        "hobbies": ["music", "hiking"],
        "interests": ["music", "nature"],
        "favoriteColors": ["blue", "green"],
        "minAge": "20",
        "maxAge": "30",
        "whatBringsYouHere": "relationship",
        "genderInterest": "female",
        "pets": ["dog"],
        "education": "Bachelor's",
        "lookingFor": ["relationship"],
        "religion": "Christian",
        "images": [
            {
                "url": "https://example.com/images/james1.jpg",
                "publicId": "james_img1"
            }
        ],
        "completionPercentage": 94
    }
]
